name: Lint Code Base

on:
  workflow_dispatch:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  cache:
    name: Cache
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p ~/super-linter
      - name: Create cache
        run: docker pull postgres:latest

      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      
      - run: docker images
