name: Lint Code Base

on:
  workflow_dispatch:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  cache:
    name: Cache
    runs-on: ubuntu-latest

    steps:
      - run: mkdir -p ~/super-linter
      - name: Cache super-linter
        id: image-cache
        uses: actions/cache@v3
        with:
          path: ~/super-linter
          key: ${{ runner.os }}-super-linter

      - name: Create cache
        if: steps.image-cache.outputs.cache-hit != 'true'
        run: |
          docker pull ghcr.io/github/super-linter:v4.9.7
          docker save -o ~/super-linter/super-linter.tar ghcr.io/github/super-linter

      - name: Load cache
        if: steps.image-cache.outputs.cache-hit == 'true'
        run: docker load -i ~/super-linter/super-linter.tar
      
      - run: docker images
